spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_web
    username: root
    password: root
#mybatis配置
mybatis-plus:
  #映射文件位置
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.weChat.po
  #原生 MyBatis 所支持的配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
  #MyBatis-Plus 全局策略配置
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
#日志级别
logging:
  level:
    org.apache.http.wire: error
    org.apache.http.headers: error
#端口
server:
  port: 8084