spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: 127.0.0.1:8048
        namespace: dbe63b4c-fa43-4eb0-ab4c-7b6f3cd71c79
  #redis
  redis:
    database: 2
    host: localhost
    port: 6379
    password: